[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10"
interactions-py = "^5.13.1"
python-dotenv = "^1.0.1"
uvloop = "^0.19.0"

[[tool.poetry.source]]
name = "tuna"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
priority = "primary"
