[project]
name = "mybot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.14",
    "interactions-py>=5.15.0",
    "python-dotenv>=1.1.1",
    "uvloop>=0.21.0",
]
